### ISSUE TITLE
Bispectrum application

### ISSUE THREAD

**Issue by StianIsmar** [synergetics/spectrum#2]
Hi, nice library. 

If I wish to compute the bispectrum (direct) for all frequencies from a signal and return a magnitude matrix, how would you do this with your library? The plots show the comparison between f1 and f2 only.

My code:
```
sig # shape 20000,
mean_amplitude = np.mean(sig)
sig = sig - mean_amplitude  # Centering around 0
fft = np.fft.fft(sig) # complex number. Magnitude and phase.
N = sig.size
T = t[1] - t[0]
f = np.linspace(0, 1 / T, N, )
f = f[:N // 2]
```
Thank you!

**Comment by ixaxaar** [comment]
Damn I dont even remember this. I'll revise on this and get back. Sorry for such a late response though.
