### ISSUE TITLE
How to install this package in pycharm?

### ISSUE THREAD

**Issue by Laichunli** [synergetics/spectrum#4]
After I downloaded the installation package from this website, I used pip install setup.py in py charm to show that it was successful, but the call was not successful (from spectrum import bicoherencex)
After multiple checks that it's not an environment configuration issue, I'm on the verge of crashing.
I tried a lot of methods to install it, but I really need this package.

Is there any good way?
（python3）

thank you！

`wrong reason`
> Using c:\programdata\anaconda3\lib\site-packages
> Searching for numpy==1.20.3
> Best match: numpy 1.20.3
> Adding numpy 1.20.3 to easy-install.pth file
> Installing f2py-script.py script to C:\ProgramData\Anaconda3\Scripts
> error: [WinError 5] access denied. : 'C:\\ProgramData\\Anaconda3\\Scripts\\f2py-script.py'

**Comment by ixaxaar** [comment]
I'm not sure this works with python3 as far as I remember, I had written this in python2.
You could always simply copy the `src` directory in your project folder and import from there:

```
from src.conventional import bicoherencex
```

though I'd say first replace all `print "etc"` to `print("etc")`
